### ISSUE TITLE
Got unexpected token ":" when loading valid json file

### ISSUE THREAD

**Issue by pietrovismara** [billtrik/karma-fixture#15]
When i try to load a json file with: `jsonFix = fixture.load('fix.json');` i get this error:
`Uncaught SyntaxError: Unexpected token :`

The file is the following:

```
{
    "test": "ok"
}

```

This is my configuration, i installed karma-fixture and both preprocessors.

```
    config.set({
        basePath: '..',
        frameworks: ['mocha', 'sinon-chai', 'fixture'],
        plugins: [
            'karma-fixture',
            'karma-html2js-preprocessor',
            'karma-json-fixtures-preprocessor'
        ],
        preprocessors: {
            'test/fixtures/*.html': ['html2js'],
            'test/fixtures/*.json': ['json_fixtures']
        },
        jsonFixturesPreprocessor: {
            variableName: '__json__'
        },        
        files: [
            {
                pattern: 'test/fixtures/**',
            },
        ],
        //...
```

 What am i doing wrong?

**Comment by pietrovismara** [comment]
+1 ?

**Comment by datatypevoid** [comment]
Any update on this issue?

**Comment by pietrovismara** [comment]
@datatypevoid Nope, i just stopped usign karma-fixture, due to no support, and not working package.

**Comment by chennighan** [comment]
@pietrovismara I've similarly tried with no luck. Horrible support for this package. Have you found another karma based solution for loading external json data?

**Comment by billtrik** [comment]
I verified the problem, but it is not due to the plugin's implementation.
It is due to your config file.

For future reference, i will be extra detailed here.
Let's imagine a folder structure like this:

```
test
->fixtures
->->json_fixture1.json
->->json
->->->json_fixture2.json
```

so we have 2 json files:

- `test/fixtures/json_fixture1.json`
- `test/fixtures/json/json_fixture1.json`

by adding this in your config:
```
files: [
  {
    pattern: 'test/fixtures/**',
  },
],
```

you load both files. 

So far so good.

But on your preprocessor config you say:
```
preprocessors: {
  ...
  'test/fixtures/*.json': ['json_fixtures']
  ...
},
```

Please note the `*.json` part. 
By doing this you tell the "json_fixtures" preprocessor to only parse the files that exist inside the "test/fixtures" folder 
and NOT any other files that might exist in any of its subdirectories. 

So the `json_fixture1.json` will be parsed and loaded properly, 
but the `json_fixture2.json` will not and it will produce the mentioned error.


If you alter your preprocessor config like this:
```
preprocessors: {
  ...
  // notice the '**/*.json' vs '*.json'
  'test/fixtures/**/*.json': ['json_fixtures']
  ...
},
```

It will parse and load properly all the json files found inside the "test/fixtures" dir,
thus solving the  problem.

**Comment by billtrik** [comment]
I am linking this on the README since it seems to be a popular problem. I am also marking this as closed. 
@pietrovismara @datatypevoid @chennighan 
If someone still has issues please let me know.
